Apply new cookiecutter
pyfar/spharpy pull request #79
Opened 2024-12-12 08:59 UTC by ahms5

2025-01-07 13:31 UTC, mberz commented
I may have made a bit of a mess when cleaning up the current state of the develop branch 💩

2025-01-07 14:15 UTC, mberz commented
There's a separate PR for adapting to the new set of ruff rules #90 
Sorry, I've had this on a branch that had no active PR assigned yet. Let's maybe keep this separate. If you want you can take over the other PR.

2025-01-07 18:14 UTC, mberz requested changes
There are a couple of things  wasn't sure about and a couple of things which have been deleted prematurely I guess ;)

2025-01-07 18:14 UTC, mberz commented on .github/ISSUE_TEMPLATE.md
> +* Did you install pyfar via pip:
```suggestion
* Did you install spharpy via pip:
```

2025-01-07 18:31 UTC, ahms5 commented on docs/Makefile
> -
from what I understand, everything except help is forwarded to sphinx in the same style, see below. I took it from pyfar, and this file has not changed since 2020, so no idea from were its coming.

2025-01-08 12:01 UTC, ahms5 commented
@mberz all comments adresse, but no idea how to revert this change of the docs/make.bat

2025-01-10 15:09 UTC, mberz approved these changes

2025-01-10 16:31 UTC, mberz commented
The issue with the contour plot seems to be caused by a change in the behavior of the interpolation of the data to a uniform grid. 
Either within the triangulation or the interpolation based on the triangulation.

2025-03-16 13:43 UTC, mberz commented
On hold, since the cookiecutter has been applied on main in #105

2025-04-24 09:48 UTC, ahms5 commented
can be closed when main is merged into develop

2025-05-30 12:23 UTC, f-brinkmann commented
closed in favor of #128

2025-05-30 12:23 UTC, closed without merging